spring.application.name=account-management-service

server.tomcat.threads.max=100
server.tomcat.threads.min-spare=10
server.tomcat.accept-count=100
server.tomcat.max-connections=1000
server.tomcat.connection-timeout=5s
server.tomcat.keep-alive-timeout=20s
server.tomcat.max-keep-alive-requests=1000
server.tomcat.max-http-form-post-size=1MB

server.max-http-request-header-size=16KB

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/banking?ApplicationName=account-management-service&tcpKeepAlive=true&reWriteBatchedInserts=true&preparedStatementCacheQueries=256&preparedStatementCacheSizeMiB=5&prepareThreshold=5}
spring.datasource.username=${DB_USERNAME:banking}
spring.datasource.password=${DB_PASSWORD:banking}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.pool-name=${spring.application.name}-hikari-pool
spring.datasource.hikari.maximum-pool-size=40
spring.datasource.hikari.minimum-idle=20
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.leak-detection-threshold=30000

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:banking}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:banking}
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true
spring.rabbitmq.connection-timeout=5s
spring.rabbitmq.requested-heartbeat=30s
spring.rabbitmq.template.retry.enabled=false
spring.rabbitmq.cache.connection.mode=channel
spring.rabbitmq.cache.channel.size=25
spring.rabbitmq.cache.channel.checkout-timeout=2s

mybatis.configuration.arg-name-based-constructor-auto-mapping=true
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.default-enum-type-handler=org.apache.ibatis.type.EnumTypeHandler
mybatis.type-handlers-package=ua.stepan.zhuk.infrastructure.typehandler

app.rabbit.exchange=banking.events
app.rabbit.queue=banking.events.audit

app.outbox.batch-size=200
app.outbox.poll-interval=100

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=never

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false
spring.flyway.validate-on-migrate=true
spring.flyway.validate-migration-naming=true
spring.flyway.fail-on-missing-locations=true

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=15s
